### ISSUE TITLE
Form display

### ISSUE THREAD

**Issue by Denmark14** [TeamLumi/luminescent-team#25]
When a Pokemon is selected, add a new row to the Pokedex, below evolutions and above learnsets.

The row must display sprites of the base form and every alternative form. The sprites must be meaningfully smaller than that of the sprite in the heading, around the same as the font size in which the form text is in.

There's no need to make this display fancy, it can simply be a list of:
`[sprite <pokemon name>], [sprite <pokemon name>], [sprite <pokemon name>]`

**Comment by Glup3** [comment]
merged
