### ISSUE TITLE
Display egg groups

### ISSUE THREAD

**Issue by Denmark14** [TeamLumi/luminescent-team#29]
Add a component, under forms, but above learnsets, that displays the egg group of the currently selected Pokemon. You can add the sprite of an egg here to clearly indicate it's purpose.

**Comment by Denmark14** [comment]
Blocked by #27 

- Requires util update
- Requires egg group names
- Ticket scope should be expanded to alert devs as to invalid egg moves (ie. can learn a move via egg that none of it's partners can learn, making it irrelevant)

**Comment by Glup3** [comment]
egg group names are still not implemented yet - we need to update game data

**Comment by Glup3** [comment]
merged
